/*
 * DNS DTC API
 * The DNS DTC is a BloxOne DDI service providing load balanced DNS resolution.   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DtcRecord
 */
public class DtcRecordTest {
    private final DtcRecord model = new DtcRecord();

    /**
     * Model tests for DtcRecord
     */
    @Test
    public void testDtcRecord() {
        // TODO: test DtcRecord
    }

    /**
     * Test the property 'dnsRdata'
     */
    @Test
    public void dnsRdataTest() {
        // TODO: test dnsRdata
    }

    /**
     * Test the property 'rdata'
     */
    @Test
    public void rdataTest() {
        // TODO: test rdata
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
