/*
 * DNS DTC API
 * The DNS DTC is a BloxOne DDI service providing load balanced DNS resolution.   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DtcHTTPHealthCheck;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DtcUpdateHTTPHealthCheckResponse
 */
public class DtcUpdateHTTPHealthCheckResponseTest {
    private final DtcUpdateHTTPHealthCheckResponse model = new DtcUpdateHTTPHealthCheckResponse();

    /**
     * Model tests for DtcUpdateHTTPHealthCheckResponse
     */
    @Test
    public void testDtcUpdateHTTPHealthCheckResponse() {
        // TODO: test DtcUpdateHTTPHealthCheckResponse
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

}
