/*
 * DNS Configuration API
 * The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ConfigExternalProvider;
import org.openapitools.client.model.ConfigForwarder;
import org.openapitools.client.model.ConfigWarning;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Forward zone
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-28T12:10:28.384903+05:30[Asia/Kolkata]", comments = "Generator version: 7.12.0")
public class ConfigForwardZone {
  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  @javax.annotation.Nullable
  private String comment;

  public static final String SERIALIZED_NAME_COMPARTMENT_ID = "compartment_id";
  @SerializedName(SERIALIZED_NAME_COMPARTMENT_ID)
  @javax.annotation.Nullable
  private String compartmentId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_DISABLED = "disabled";
  @SerializedName(SERIALIZED_NAME_DISABLED)
  @javax.annotation.Nullable
  private Boolean disabled;

  public static final String SERIALIZED_NAME_EXTERNAL_FORWARDERS = "external_forwarders";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_FORWARDERS)
  @javax.annotation.Nullable
  private List<ConfigForwarder> externalForwarders = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXTERNAL_PROVIDERS = "external_providers";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_PROVIDERS)
  @javax.annotation.Nullable
  private List<ConfigExternalProvider> externalProviders = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXTERNAL_PROVIDERS_METADATA = "external_providers_metadata";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_PROVIDERS_METADATA)
  @javax.annotation.Nullable
  private Object externalProvidersMetadata;

  public static final String SERIALIZED_NAME_FORWARD_ONLY = "forward_only";
  @SerializedName(SERIALIZED_NAME_FORWARD_ONLY)
  @javax.annotation.Nullable
  private Boolean forwardOnly;

  public static final String SERIALIZED_NAME_FQDN = "fqdn";
  @SerializedName(SERIALIZED_NAME_FQDN)
  @javax.annotation.Nonnull
  private String fqdn;

  public static final String SERIALIZED_NAME_HOSTS = "hosts";
  @SerializedName(SERIALIZED_NAME_HOSTS)
  @javax.annotation.Nullable
  private List<String> hosts = new ArrayList<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_INTERNAL_FORWARDERS = "internal_forwarders";
  @SerializedName(SERIALIZED_NAME_INTERNAL_FORWARDERS)
  @javax.annotation.Nullable
  private List<String> internalForwarders = new ArrayList<>();

  public static final String SERIALIZED_NAME_MAPPED_SUBNET = "mapped_subnet";
  @SerializedName(SERIALIZED_NAME_MAPPED_SUBNET)
  @javax.annotation.Nullable
  private String mappedSubnet;

  public static final String SERIALIZED_NAME_MAPPING = "mapping";
  @SerializedName(SERIALIZED_NAME_MAPPING)
  @javax.annotation.Nullable
  private String mapping;

  public static final String SERIALIZED_NAME_NIOS_GRIDS_METADATA = "nios_grids_metadata";
  @SerializedName(SERIALIZED_NAME_NIOS_GRIDS_METADATA)
  @javax.annotation.Nullable
  private Object niosGridsMetadata;

  public static final String SERIALIZED_NAME_NSGS = "nsgs";
  @SerializedName(SERIALIZED_NAME_NSGS)
  @javax.annotation.Nullable
  private List<String> nsgs = new ArrayList<>();

  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  @javax.annotation.Nullable
  private String parent;

  public static final String SERIALIZED_NAME_PROTOCOL_FQDN = "protocol_fqdn";
  @SerializedName(SERIALIZED_NAME_PROTOCOL_FQDN)
  @javax.annotation.Nullable
  private String protocolFqdn;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private Object tags;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_VIEW = "view";
  @SerializedName(SERIALIZED_NAME_VIEW)
  @javax.annotation.Nullable
  private String view;

  public static final String SERIALIZED_NAME_WARNINGS = "warnings";
  @SerializedName(SERIALIZED_NAME_WARNINGS)
  @javax.annotation.Nullable
  private List<ConfigWarning> warnings = new ArrayList<>();

  public ConfigForwardZone() {
  }

  public ConfigForwardZone(
     OffsetDateTime createdAt, 
     List<ConfigExternalProvider> externalProviders, 
     String id, 
     String mappedSubnet, 
     String mapping, 
     String protocolFqdn, 
     OffsetDateTime updatedAt, 
     List<ConfigWarning> warnings
  ) {
    this();
    this.createdAt = createdAt;
    this.externalProviders = externalProviders;
    this.id = id;
    this.mappedSubnet = mappedSubnet;
    this.mapping = mapping;
    this.protocolFqdn = protocolFqdn;
    this.updatedAt = updatedAt;
    this.warnings = warnings;
  }

  public ConfigForwardZone comment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Optional. Comment for zone configuration.
   * @return comment
   */
  @javax.annotation.Nullable
  public String getComment() {
    return comment;
  }

  public void setComment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
  }


  public ConfigForwardZone compartmentId(@javax.annotation.Nullable String compartmentId) {
    this.compartmentId = compartmentId;
    return this;
  }

  /**
   * The access view associated with the object. If no access view is associated with the object, the value defaults to empty.
   * @return compartmentId
   */
  @javax.annotation.Nullable
  public String getCompartmentId() {
    return compartmentId;
  }

  public void setCompartmentId(@javax.annotation.Nullable String compartmentId) {
    this.compartmentId = compartmentId;
  }


  /**
   * The timestamp when the object has been created.
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  public ConfigForwardZone disabled(@javax.annotation.Nullable Boolean disabled) {
    this.disabled = disabled;
    return this;
  }

  /**
   * Optional. _true_ to disable object. A disabled object is effectively non-existent when generating configuration.
   * @return disabled
   */
  @javax.annotation.Nullable
  public Boolean getDisabled() {
    return disabled;
  }

  public void setDisabled(@javax.annotation.Nullable Boolean disabled) {
    this.disabled = disabled;
  }


  public ConfigForwardZone externalForwarders(@javax.annotation.Nullable List<ConfigForwarder> externalForwarders) {
    this.externalForwarders = externalForwarders;
    return this;
  }

  public ConfigForwardZone addExternalForwardersItem(ConfigForwarder externalForwardersItem) {
    if (this.externalForwarders == null) {
      this.externalForwarders = new ArrayList<>();
    }
    this.externalForwarders.add(externalForwardersItem);
    return this;
  }

  /**
   * Optional. External DNS servers to forward to. Order is not significant.
   * @return externalForwarders
   */
  @javax.annotation.Nullable
  public List<ConfigForwarder> getExternalForwarders() {
    return externalForwarders;
  }

  public void setExternalForwarders(@javax.annotation.Nullable List<ConfigForwarder> externalForwarders) {
    this.externalForwarders = externalForwarders;
  }


  /**
   * list of external providers for the forward zone.
   * @return externalProviders
   */
  @javax.annotation.Nullable
  public List<ConfigExternalProvider> getExternalProviders() {
    return externalProviders;
  }



  public ConfigForwardZone externalProvidersMetadata(@javax.annotation.Nullable Object externalProvidersMetadata) {
    this.externalProvidersMetadata = externalProvidersMetadata;
    return this;
  }

  /**
   * External DNS providers metadata.
   * @return externalProvidersMetadata
   */
  @javax.annotation.Nullable
  public Object getExternalProvidersMetadata() {
    return externalProvidersMetadata;
  }

  public void setExternalProvidersMetadata(@javax.annotation.Nullable Object externalProvidersMetadata) {
    this.externalProvidersMetadata = externalProvidersMetadata;
  }


  public ConfigForwardZone forwardOnly(@javax.annotation.Nullable Boolean forwardOnly) {
    this.forwardOnly = forwardOnly;
    return this;
  }

  /**
   * Optional. _true_ to only forward.
   * @return forwardOnly
   */
  @javax.annotation.Nullable
  public Boolean getForwardOnly() {
    return forwardOnly;
  }

  public void setForwardOnly(@javax.annotation.Nullable Boolean forwardOnly) {
    this.forwardOnly = forwardOnly;
  }


  public ConfigForwardZone fqdn(@javax.annotation.Nonnull String fqdn) {
    this.fqdn = fqdn;
    return this;
  }

  /**
   * Zone FQDN. The FQDN supplied at creation will be converted to canonical form.  Read-only after creation.
   * @return fqdn
   */
  @javax.annotation.Nonnull
  public String getFqdn() {
    return fqdn;
  }

  public void setFqdn(@javax.annotation.Nonnull String fqdn) {
    this.fqdn = fqdn;
  }


  public ConfigForwardZone hosts(@javax.annotation.Nullable List<String> hosts) {
    this.hosts = hosts;
    return this;
  }

  public ConfigForwardZone addHostsItem(String hostsItem) {
    if (this.hosts == null) {
      this.hosts = new ArrayList<>();
    }
    this.hosts.add(hostsItem);
    return this;
  }

  /**
   * The resource identifier.
   * @return hosts
   */
  @javax.annotation.Nullable
  public List<String> getHosts() {
    return hosts;
  }

  public void setHosts(@javax.annotation.Nullable List<String> hosts) {
    this.hosts = hosts;
  }


  /**
   * The resource identifier.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }



  public ConfigForwardZone internalForwarders(@javax.annotation.Nullable List<String> internalForwarders) {
    this.internalForwarders = internalForwarders;
    return this;
  }

  public ConfigForwardZone addInternalForwardersItem(String internalForwardersItem) {
    if (this.internalForwarders == null) {
      this.internalForwarders = new ArrayList<>();
    }
    this.internalForwarders.add(internalForwardersItem);
    return this;
  }

  /**
   * The resource identifier.
   * @return internalForwarders
   */
  @javax.annotation.Nullable
  public List<String> getInternalForwarders() {
    return internalForwarders;
  }

  public void setInternalForwarders(@javax.annotation.Nullable List<String> internalForwarders) {
    this.internalForwarders = internalForwarders;
  }


  /**
   * Reverse zone network address in the following format: \&quot;ip-address/cidr\&quot;. Defaults to empty.
   * @return mappedSubnet
   */
  @javax.annotation.Nullable
  public String getMappedSubnet() {
    return mappedSubnet;
  }



  /**
   * Read-only. Zone mapping type. Allowed values:  * _forward_,  * _ipv4_reverse_.  * _ipv6_reverse_.  Defaults to _forward_.
   * @return mapping
   */
  @javax.annotation.Nullable
  public String getMapping() {
    return mapping;
  }



  public ConfigForwardZone niosGridsMetadata(@javax.annotation.Nullable Object niosGridsMetadata) {
    this.niosGridsMetadata = niosGridsMetadata;
    return this;
  }

  /**
   * NIOS Grids Metadata holds multiple NIOS grids data.
   * @return niosGridsMetadata
   */
  @javax.annotation.Nullable
  public Object getNiosGridsMetadata() {
    return niosGridsMetadata;
  }

  public void setNiosGridsMetadata(@javax.annotation.Nullable Object niosGridsMetadata) {
    this.niosGridsMetadata = niosGridsMetadata;
  }


  public ConfigForwardZone nsgs(@javax.annotation.Nullable List<String> nsgs) {
    this.nsgs = nsgs;
    return this;
  }

  public ConfigForwardZone addNsgsItem(String nsgsItem) {
    if (this.nsgs == null) {
      this.nsgs = new ArrayList<>();
    }
    this.nsgs.add(nsgsItem);
    return this;
  }

  /**
   * The resource identifier.
   * @return nsgs
   */
  @javax.annotation.Nullable
  public List<String> getNsgs() {
    return nsgs;
  }

  public void setNsgs(@javax.annotation.Nullable List<String> nsgs) {
    this.nsgs = nsgs;
  }


  public ConfigForwardZone parent(@javax.annotation.Nullable String parent) {
    this.parent = parent;
    return this;
  }

  /**
   * The resource identifier.
   * @return parent
   */
  @javax.annotation.Nullable
  public String getParent() {
    return parent;
  }

  public void setParent(@javax.annotation.Nullable String parent) {
    this.parent = parent;
  }


  /**
   * Zone FQDN in punycode.
   * @return protocolFqdn
   */
  @javax.annotation.Nullable
  public String getProtocolFqdn() {
    return protocolFqdn;
  }



  public ConfigForwardZone tags(@javax.annotation.Nullable Object tags) {
    this.tags = tags;
    return this;
  }

  /**
   * Tagging specifics.
   * @return tags
   */
  @javax.annotation.Nullable
  public Object getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable Object tags) {
    this.tags = tags;
  }


  /**
   * The timestamp when the object has been updated. Equals to _created_at_ if not updated after creation.
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }



  public ConfigForwardZone view(@javax.annotation.Nullable String view) {
    this.view = view;
    return this;
  }

  /**
   * The resource identifier.
   * @return view
   */
  @javax.annotation.Nullable
  public String getView() {
    return view;
  }

  public void setView(@javax.annotation.Nullable String view) {
    this.view = view;
  }


  /**
   * The list of a forward zone warnings.
   * @return warnings
   */
  @javax.annotation.Nullable
  public List<ConfigWarning> getWarnings() {
    return warnings;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigForwardZone configForwardZone = (ConfigForwardZone) o;
    return Objects.equals(this.comment, configForwardZone.comment) &&
        Objects.equals(this.compartmentId, configForwardZone.compartmentId) &&
        Objects.equals(this.createdAt, configForwardZone.createdAt) &&
        Objects.equals(this.disabled, configForwardZone.disabled) &&
        Objects.equals(this.externalForwarders, configForwardZone.externalForwarders) &&
        Objects.equals(this.externalProviders, configForwardZone.externalProviders) &&
        Objects.equals(this.externalProvidersMetadata, configForwardZone.externalProvidersMetadata) &&
        Objects.equals(this.forwardOnly, configForwardZone.forwardOnly) &&
        Objects.equals(this.fqdn, configForwardZone.fqdn) &&
        Objects.equals(this.hosts, configForwardZone.hosts) &&
        Objects.equals(this.id, configForwardZone.id) &&
        Objects.equals(this.internalForwarders, configForwardZone.internalForwarders) &&
        Objects.equals(this.mappedSubnet, configForwardZone.mappedSubnet) &&
        Objects.equals(this.mapping, configForwardZone.mapping) &&
        Objects.equals(this.niosGridsMetadata, configForwardZone.niosGridsMetadata) &&
        Objects.equals(this.nsgs, configForwardZone.nsgs) &&
        Objects.equals(this.parent, configForwardZone.parent) &&
        Objects.equals(this.protocolFqdn, configForwardZone.protocolFqdn) &&
        Objects.equals(this.tags, configForwardZone.tags) &&
        Objects.equals(this.updatedAt, configForwardZone.updatedAt) &&
        Objects.equals(this.view, configForwardZone.view) &&
        Objects.equals(this.warnings, configForwardZone.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, compartmentId, createdAt, disabled, externalForwarders, externalProviders, externalProvidersMetadata, forwardOnly, fqdn, hosts, id, internalForwarders, mappedSubnet, mapping, niosGridsMetadata, nsgs, parent, protocolFqdn, tags, updatedAt, view, warnings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigForwardZone {\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    compartmentId: ").append(toIndentedString(compartmentId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    externalForwarders: ").append(toIndentedString(externalForwarders)).append("\n");
    sb.append("    externalProviders: ").append(toIndentedString(externalProviders)).append("\n");
    sb.append("    externalProvidersMetadata: ").append(toIndentedString(externalProvidersMetadata)).append("\n");
    sb.append("    forwardOnly: ").append(toIndentedString(forwardOnly)).append("\n");
    sb.append("    fqdn: ").append(toIndentedString(fqdn)).append("\n");
    sb.append("    hosts: ").append(toIndentedString(hosts)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    internalForwarders: ").append(toIndentedString(internalForwarders)).append("\n");
    sb.append("    mappedSubnet: ").append(toIndentedString(mappedSubnet)).append("\n");
    sb.append("    mapping: ").append(toIndentedString(mapping)).append("\n");
    sb.append("    niosGridsMetadata: ").append(toIndentedString(niosGridsMetadata)).append("\n");
    sb.append("    nsgs: ").append(toIndentedString(nsgs)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    protocolFqdn: ").append(toIndentedString(protocolFqdn)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    view: ").append(toIndentedString(view)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("comment");
    openapiFields.add("compartment_id");
    openapiFields.add("created_at");
    openapiFields.add("disabled");
    openapiFields.add("external_forwarders");
    openapiFields.add("external_providers");
    openapiFields.add("external_providers_metadata");
    openapiFields.add("forward_only");
    openapiFields.add("fqdn");
    openapiFields.add("hosts");
    openapiFields.add("id");
    openapiFields.add("internal_forwarders");
    openapiFields.add("mapped_subnet");
    openapiFields.add("mapping");
    openapiFields.add("nios_grids_metadata");
    openapiFields.add("nsgs");
    openapiFields.add("parent");
    openapiFields.add("protocol_fqdn");
    openapiFields.add("tags");
    openapiFields.add("updated_at");
    openapiFields.add("view");
    openapiFields.add("warnings");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("fqdn");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConfigForwardZone
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConfigForwardZone.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConfigForwardZone is not found in the empty JSON string", ConfigForwardZone.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConfigForwardZone.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConfigForwardZone` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConfigForwardZone.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
      if ((jsonObj.get("compartment_id") != null && !jsonObj.get("compartment_id").isJsonNull()) && !jsonObj.get("compartment_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `compartment_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("compartment_id").toString()));
      }
      if (jsonObj.get("external_forwarders") != null && !jsonObj.get("external_forwarders").isJsonNull()) {
        JsonArray jsonArrayexternalForwarders = jsonObj.getAsJsonArray("external_forwarders");
        if (jsonArrayexternalForwarders != null) {
          // ensure the json data is an array
          if (!jsonObj.get("external_forwarders").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `external_forwarders` to be an array in the JSON string but got `%s`", jsonObj.get("external_forwarders").toString()));
          }

          // validate the optional field `external_forwarders` (array)
          for (int i = 0; i < jsonArrayexternalForwarders.size(); i++) {
            ConfigForwarder.validateJsonElement(jsonArrayexternalForwarders.get(i));
          };
        }
      }
      if (jsonObj.get("external_providers") != null && !jsonObj.get("external_providers").isJsonNull()) {
        JsonArray jsonArrayexternalProviders = jsonObj.getAsJsonArray("external_providers");
        if (jsonArrayexternalProviders != null) {
          // ensure the json data is an array
          if (!jsonObj.get("external_providers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `external_providers` to be an array in the JSON string but got `%s`", jsonObj.get("external_providers").toString()));
          }

          // validate the optional field `external_providers` (array)
          for (int i = 0; i < jsonArrayexternalProviders.size(); i++) {
            ConfigExternalProvider.validateJsonElement(jsonArrayexternalProviders.get(i));
          };
        }
      }
      if (!jsonObj.get("fqdn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fqdn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fqdn").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("hosts") != null && !jsonObj.get("hosts").isJsonNull() && !jsonObj.get("hosts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `hosts` to be an array in the JSON string but got `%s`", jsonObj.get("hosts").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("internal_forwarders") != null && !jsonObj.get("internal_forwarders").isJsonNull() && !jsonObj.get("internal_forwarders").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `internal_forwarders` to be an array in the JSON string but got `%s`", jsonObj.get("internal_forwarders").toString()));
      }
      if ((jsonObj.get("mapped_subnet") != null && !jsonObj.get("mapped_subnet").isJsonNull()) && !jsonObj.get("mapped_subnet").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mapped_subnet` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mapped_subnet").toString()));
      }
      if ((jsonObj.get("mapping") != null && !jsonObj.get("mapping").isJsonNull()) && !jsonObj.get("mapping").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mapping` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mapping").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("nsgs") != null && !jsonObj.get("nsgs").isJsonNull() && !jsonObj.get("nsgs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `nsgs` to be an array in the JSON string but got `%s`", jsonObj.get("nsgs").toString()));
      }
      if ((jsonObj.get("parent") != null && !jsonObj.get("parent").isJsonNull()) && !jsonObj.get("parent").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `parent` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parent").toString()));
      }
      if ((jsonObj.get("protocol_fqdn") != null && !jsonObj.get("protocol_fqdn").isJsonNull()) && !jsonObj.get("protocol_fqdn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `protocol_fqdn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("protocol_fqdn").toString()));
      }
      if ((jsonObj.get("view") != null && !jsonObj.get("view").isJsonNull()) && !jsonObj.get("view").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `view` to be a primitive type in the JSON string but got `%s`", jsonObj.get("view").toString()));
      }
      if (jsonObj.get("warnings") != null && !jsonObj.get("warnings").isJsonNull()) {
        JsonArray jsonArraywarnings = jsonObj.getAsJsonArray("warnings");
        if (jsonArraywarnings != null) {
          // ensure the json data is an array
          if (!jsonObj.get("warnings").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `warnings` to be an array in the JSON string but got `%s`", jsonObj.get("warnings").toString()));
          }

          // validate the optional field `warnings` (array)
          for (int i = 0; i < jsonArraywarnings.size(); i++) {
            ConfigWarning.validateJsonElement(jsonArraywarnings.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConfigForwardZone.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConfigForwardZone' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConfigForwardZone> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConfigForwardZone.class));

       return (TypeAdapter<T>) new TypeAdapter<ConfigForwardZone>() {
           @Override
           public void write(JsonWriter out, ConfigForwardZone value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConfigForwardZone read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConfigForwardZone given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConfigForwardZone
   * @throws IOException if the JSON string is invalid with respect to ConfigForwardZone
   */
  public static ConfigForwardZone fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConfigForwardZone.class);
  }

  /**
   * Convert an instance of ConfigForwardZone to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

