/*
 * IP Address Management API
 * The IPAM/DHCP Application is a BloxOne DDI service providing IP address management and DHCP protocol features. The IPAM component provides visibility into and provisioning tools to manage networking spaces, monitoring and reporting of entire IP address infrastructures, and integration with DNS and DHCP protocols. The DHCP component provides DHCP protocol configuration service with on-prem host serving DHCP protocol. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IpamsvcDHCPInfo
 */
public class IpamsvcDHCPInfoTest {
    private final IpamsvcDHCPInfo model = new IpamsvcDHCPInfo();

    /**
     * Model tests for IpamsvcDHCPInfo
     */
    @Test
    public void testIpamsvcDHCPInfo() {
        // TODO: test IpamsvcDHCPInfo
    }

    /**
     * Test the property 'clientHostname'
     */
    @Test
    public void clientHostnameTest() {
        // TODO: test clientHostname
    }

    /**
     * Test the property 'clientHwaddr'
     */
    @Test
    public void clientHwaddrTest() {
        // TODO: test clientHwaddr
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'fingerprint'
     */
    @Test
    public void fingerprintTest() {
        // TODO: test fingerprint
    }

    /**
     * Test the property 'iaid'
     */
    @Test
    public void iaidTest() {
        // TODO: test iaid
    }

    /**
     * Test the property 'leaseType'
     */
    @Test
    public void leaseTypeTest() {
        // TODO: test leaseType
    }

    /**
     * Test the property 'preferredLifetime'
     */
    @Test
    public void preferredLifetimeTest() {
        // TODO: test preferredLifetime
    }

    /**
     * Test the property 'remain'
     */
    @Test
    public void remainTest() {
        // TODO: test remain
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'stateTs'
     */
    @Test
    public void stateTsTest() {
        // TODO: test stateTs
    }

}
