/*
 * IP Address Management API
 * The IPAM/DHCP Application is a BloxOne DDI service providing IP address management and DHCP protocol features. The IPAM component provides visibility into and provisioning tools to manage networking spaces, monitoring and reporting of entire IP address infrastructures, and integration with DNS and DHCP protocols. The DHCP component provides DHCP protocol configuration service with on-prem host serving DHCP protocol. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.IpamsvcAddressBlock;
import org.openapitools.client.model.IpamsvcIPSpace;
import org.openapitools.client.model.IpamsvcRange;
import org.openapitools.client.model.IpamsvcSubnet;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IpamsvcDHCPCapabilityAssociationsResponse
 */
public class IpamsvcDHCPCapabilityAssociationsResponseTest {
    private final IpamsvcDHCPCapabilityAssociationsResponse model = new IpamsvcDHCPCapabilityAssociationsResponse();

    /**
     * Model tests for IpamsvcDHCPCapabilityAssociationsResponse
     */
    @Test
    public void testIpamsvcDHCPCapabilityAssociationsResponse() {
        // TODO: test IpamsvcDHCPCapabilityAssociationsResponse
    }

    /**
     * Test the property 'addressBlocks'
     */
    @Test
    public void addressBlocksTest() {
        // TODO: test addressBlocks
    }

    /**
     * Test the property 'ipSpace'
     */
    @Test
    public void ipSpaceTest() {
        // TODO: test ipSpace
    }

    /**
     * Test the property 'ranges'
     */
    @Test
    public void rangesTest() {
        // TODO: test ranges
    }

    /**
     * Test the property 'subnets'
     */
    @Test
    public void subnetsTest() {
        // TODO: test subnets
    }

}
