/*
 * DNS Configuration API
 * The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ConfigFTCConfig;
import org.openapitools.client.model.ConfigHostAssociatedServer;
import org.openapitools.client.model.ConfigHostInheritance;
import org.openapitools.client.model.ConfigHostInterface;
import org.openapitools.client.model.ConfigKerberosKey;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConfigHost
 */
public class ConfigHostTest {
    private final ConfigHost model = new ConfigHost();

    /**
     * Model tests for ConfigHost
     */
    @Test
    public void testConfigHost() {
        // TODO: test ConfigHost
    }

    /**
     * Test the property 'absoluteName'
     */
    @Test
    public void absoluteNameTest() {
        // TODO: test absoluteName
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'anycastAddresses'
     */
    @Test
    public void anycastAddressesTest() {
        // TODO: test anycastAddresses
    }

    /**
     * Test the property 'associatedServer'
     */
    @Test
    public void associatedServerTest() {
        // TODO: test associatedServer
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'currentVersion'
     */
    @Test
    public void currentVersionTest() {
        // TODO: test currentVersion
    }

    /**
     * Test the property 'dfp'
     */
    @Test
    public void dfpTest() {
        // TODO: test dfp
    }

    /**
     * Test the property 'dfpService'
     */
    @Test
    public void dfpServiceTest() {
        // TODO: test dfpService
    }

    /**
     * Test the property 'externalProvidersMetadata'
     */
    @Test
    public void externalProvidersMetadataTest() {
        // TODO: test externalProvidersMetadata
    }

    /**
     * Test the property 'faultTolerantCaching'
     */
    @Test
    public void faultTolerantCachingTest() {
        // TODO: test faultTolerantCaching
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'inheritanceSources'
     */
    @Test
    public void inheritanceSourcesTest() {
        // TODO: test inheritanceSources
    }

    /**
     * Test the property 'interfaces'
     */
    @Test
    public void interfacesTest() {
        // TODO: test interfaces
    }

    /**
     * Test the property 'kerberosKeys'
     */
    @Test
    public void kerberosKeysTest() {
        // TODO: test kerberosKeys
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ophid'
     */
    @Test
    public void ophidTest() {
        // TODO: test ophid
    }

    /**
     * Test the property 'protocolAbsoluteName'
     */
    @Test
    public void protocolAbsoluteNameTest() {
        // TODO: test protocolAbsoluteName
    }

    /**
     * Test the property 'providerId'
     */
    @Test
    public void providerIdTest() {
        // TODO: test providerId
    }

    /**
     * Test the property 'server'
     */
    @Test
    public void serverTest() {
        // TODO: test server
    }

    /**
     * Test the property 'siteId'
     */
    @Test
    public void siteIdTest() {
        // TODO: test siteId
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
