/*
 * DNS Configuration API
 * The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ConfigAuthZoneConfig;
import org.openapitools.client.model.ConfigForwardZoneConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConfigBulkCopyView
 */
public class ConfigBulkCopyViewTest {
    private final ConfigBulkCopyView model = new ConfigBulkCopyView();

    /**
     * Model tests for ConfigBulkCopyView
     */
    @Test
    public void testConfigBulkCopyView() {
        // TODO: test ConfigBulkCopyView
    }

    /**
     * Test the property 'authZoneConfig'
     */
    @Test
    public void authZoneConfigTest() {
        // TODO: test authZoneConfig
    }

    /**
     * Test the property 'forwardZoneConfig'
     */
    @Test
    public void forwardZoneConfigTest() {
        // TODO: test forwardZoneConfig
    }

    /**
     * Test the property 'recursive'
     */
    @Test
    public void recursiveTest() {
        // TODO: test recursive
    }

    /**
     * Test the property 'resources'
     */
    @Test
    public void resourcesTest() {
        // TODO: test resources
    }

    /**
     * Test the property 'secondaryZoneConfig'
     */
    @Test
    public void secondaryZoneConfigTest() {
        // TODO: test secondaryZoneConfig
    }

    /**
     * Test the property 'skipOnError'
     */
    @Test
    public void skipOnErrorTest() {
        // TODO: test skipOnError
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

}
