/*
 * DNS Configuration API
 * The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.   
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ConfigAssociatedHost;
import org.openapitools.client.model.ConfigHostAssociatedServer;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConfigServiceInstance
 */
public class ConfigServiceInstanceTest {
    private final ConfigServiceInstance model = new ConfigServiceInstance();

    /**
     * Model tests for ConfigServiceInstance
     */
    @Test
    public void testConfigServiceInstance() {
        // TODO: test ConfigServiceInstance
    }

    /**
     * Test the property 'absoluteName'
     */
    @Test
    public void absoluteNameTest() {
        // TODO: test absoluteName
    }

    /**
     * Test the property 'associatedHosts'
     */
    @Test
    public void associatedHostsTest() {
        // TODO: test associatedHosts
    }

    /**
     * Test the property 'associatedServer'
     */
    @Test
    public void associatedServerTest() {
        // TODO: test associatedServer
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'protocolAbsoluteName'
     */
    @Test
    public void protocolAbsoluteNameTest() {
        // TODO: test protocolAbsoluteName
    }

    /**
     * Test the property 'providerId'
     */
    @Test
    public void providerIdTest() {
        // TODO: test providerId
    }

    /**
     * Test the property 'providerType'
     */
    @Test
    public void providerTypeTest() {
        // TODO: test providerType
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
