/*
 * IP Address Management Web API
 * The WAPI Portal provides access to the IPAM/DHCP Application, a BloxOne DDI service providing IP address management and DHCP protocol features
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * An __IPv6Range__ object (_ipv6range_) represents a set of contiguous IPv6 addresses in the same IP space with no gap, expressed as a (start_addr, end_addr) pair within a given network that are grouped together for administrative purpose and protocol management. The start and end values are not required to align with CIDR boundaries.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-28T12:10:33.825954+05:30[Asia/Kolkata]", comments = "Generator version: 7.12.0")
public class V3IPv6Range {
  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  @javax.annotation.Nullable
  private String comment;

  public static final String SERIALIZED_NAME_END_ADDR = "end_addr";
  @SerializedName(SERIALIZED_NAME_END_ADDR)
  @javax.annotation.Nonnull
  private String endAddr;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  @javax.annotation.Nullable
  private String network;

  public static final String SERIALIZED_NAME_NETWORK_VIEW = "network_view";
  @SerializedName(SERIALIZED_NAME_NETWORK_VIEW)
  @javax.annotation.Nonnull
  private String networkView;

  public static final String SERIALIZED_NAME_REF = "ref";
  @SerializedName(SERIALIZED_NAME_REF)
  @javax.annotation.Nullable
  private String ref;

  public static final String SERIALIZED_NAME_START_ADDR = "start_addr";
  @SerializedName(SERIALIZED_NAME_START_ADDR)
  @javax.annotation.Nonnull
  private String startAddr;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private Object tags;

  public V3IPv6Range() {
  }

  public V3IPv6Range(
     String network
  ) {
    this();
    this.network = network;
  }

  public V3IPv6Range comment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Comment for the range; maximum 1024 characters.
   * @return comment
   */
  @javax.annotation.Nullable
  public String getComment() {
    return comment;
  }

  public void setComment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
  }


  public V3IPv6Range endAddr(@javax.annotation.Nonnull String endAddr) {
    this.endAddr = endAddr;
    return this;
  }

  /**
   * The IPv6 Address end address of the DHCP IPv6 range.
   * @return endAddr
   */
  @javax.annotation.Nonnull
  public String getEndAddr() {
    return endAddr;
  }

  public void setEndAddr(@javax.annotation.Nonnull String endAddr) {
    this.endAddr = endAddr;
  }


  /**
   * The network this range belongs to, in IPv6 Address/CIDR format.
   * @return network
   */
  @javax.annotation.Nullable
  public String getNetwork() {
    return network;
  }



  public V3IPv6Range networkView(@javax.annotation.Nonnull String networkView) {
    this.networkView = networkView;
    return this;
  }

  /**
   * The name of the network view in which this range resides.
   * @return networkView
   */
  @javax.annotation.Nonnull
  public String getNetworkView() {
    return networkView;
  }

  public void setNetworkView(@javax.annotation.Nonnull String networkView) {
    this.networkView = networkView;
  }


  public V3IPv6Range ref(@javax.annotation.Nullable String ref) {
    this.ref = ref;
    return this;
  }

  /**
   * infoblox.ddi.wapi.objectref
   * @return ref
   */
  @javax.annotation.Nullable
  public String getRef() {
    return ref;
  }

  public void setRef(@javax.annotation.Nullable String ref) {
    this.ref = ref;
  }


  public V3IPv6Range startAddr(@javax.annotation.Nonnull String startAddr) {
    this.startAddr = startAddr;
    return this;
  }

  /**
   * The IPv6 Address starting address of the DHCP IPv6 range.
   * @return startAddr
   */
  @javax.annotation.Nonnull
  public String getStartAddr() {
    return startAddr;
  }

  public void setStartAddr(@javax.annotation.Nonnull String startAddr) {
    this.startAddr = startAddr;
  }


  public V3IPv6Range tags(@javax.annotation.Nullable Object tags) {
    this.tags = tags;
    return this;
  }

  /**
   * The tags for the range in JSON format.
   * @return tags
   */
  @javax.annotation.Nullable
  public Object getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable Object tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V3IPv6Range v3IPv6Range = (V3IPv6Range) o;
    return Objects.equals(this.comment, v3IPv6Range.comment) &&
        Objects.equals(this.endAddr, v3IPv6Range.endAddr) &&
        Objects.equals(this.network, v3IPv6Range.network) &&
        Objects.equals(this.networkView, v3IPv6Range.networkView) &&
        Objects.equals(this.ref, v3IPv6Range.ref) &&
        Objects.equals(this.startAddr, v3IPv6Range.startAddr) &&
        Objects.equals(this.tags, v3IPv6Range.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, endAddr, network, networkView, ref, startAddr, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V3IPv6Range {\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    endAddr: ").append(toIndentedString(endAddr)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    networkView: ").append(toIndentedString(networkView)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    startAddr: ").append(toIndentedString(startAddr)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("comment");
    openapiFields.add("end_addr");
    openapiFields.add("network");
    openapiFields.add("network_view");
    openapiFields.add("ref");
    openapiFields.add("start_addr");
    openapiFields.add("tags");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("end_addr");
    openapiRequiredFields.add("network_view");
    openapiRequiredFields.add("start_addr");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V3IPv6Range
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V3IPv6Range.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V3IPv6Range is not found in the empty JSON string", V3IPv6Range.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V3IPv6Range.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V3IPv6Range` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V3IPv6Range.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
      if (!jsonObj.get("end_addr").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `end_addr` to be a primitive type in the JSON string but got `%s`", jsonObj.get("end_addr").toString()));
      }
      if ((jsonObj.get("network") != null && !jsonObj.get("network").isJsonNull()) && !jsonObj.get("network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network").toString()));
      }
      if (!jsonObj.get("network_view").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `network_view` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network_view").toString()));
      }
      if ((jsonObj.get("ref") != null && !jsonObj.get("ref").isJsonNull()) && !jsonObj.get("ref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ref").toString()));
      }
      if (!jsonObj.get("start_addr").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `start_addr` to be a primitive type in the JSON string but got `%s`", jsonObj.get("start_addr").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V3IPv6Range.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V3IPv6Range' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V3IPv6Range> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V3IPv6Range.class));

       return (TypeAdapter<T>) new TypeAdapter<V3IPv6Range>() {
           @Override
           public void write(JsonWriter out, V3IPv6Range value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V3IPv6Range read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V3IPv6Range given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V3IPv6Range
   * @throws IOException if the JSON string is invalid with respect to V3IPv6Range
   */
  public static V3IPv6Range fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V3IPv6Range.class);
  }

  /**
   * Convert an instance of V3IPv6Range to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

