/*
 * Discovery Configuration API V2
 * The Discovery configuration service is a BloxOne Service that provides configuration for accessing and syncing the Cloud assets   Base Paths:  1. provider: **_/api/cloud_discovery/v2/_**  
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DdidnsrickettsAccount;
import org.openapitools.client.model.DdidnsrickettsCredentialConfig;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Source configuration
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-28T12:10:24.110229+05:30[Asia/Kolkata]", comments = "Generator version: 7.12.0")
public class DdidnsrickettsSourceConfig {
  public static final String SERIALIZED_NAME_ACCOUNT_SCHEDULE_ID = "account_schedule_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_SCHEDULE_ID)
  @javax.annotation.Nullable
  private String accountScheduleId;

  public static final String SERIALIZED_NAME_ACCOUNTS = "accounts";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS)
  @javax.annotation.Nullable
  private List<DdidnsrickettsAccount> accounts = new ArrayList<>();

  public static final String SERIALIZED_NAME_CLOUD_CREDENTIAL_ID = "cloud_credential_id";
  @SerializedName(SERIALIZED_NAME_CLOUD_CREDENTIAL_ID)
  @javax.annotation.Nonnull
  private String cloudCredentialId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_CREDENTIAL_CONFIG = "credential_config";
  @SerializedName(SERIALIZED_NAME_CREDENTIAL_CONFIG)
  @javax.annotation.Nullable
  private DdidnsrickettsCredentialConfig credentialConfig;

  public static final String SERIALIZED_NAME_DELETED_AT = "deleted_at";
  @SerializedName(SERIALIZED_NAME_DELETED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_RESTRICTED_TO_ACCOUNTS = "restricted_to_accounts";
  @SerializedName(SERIALIZED_NAME_RESTRICTED_TO_ACCOUNTS)
  @javax.annotation.Nullable
  private List<String> restrictedToAccounts = new ArrayList<>();

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public DdidnsrickettsSourceConfig() {
  }

  public DdidnsrickettsSourceConfig(
     String accountScheduleId, 
     OffsetDateTime createdAt, 
     OffsetDateTime deletedAt, 
     String id, 
     OffsetDateTime updatedAt
  ) {
    this();
    this.accountScheduleId = accountScheduleId;
    this.createdAt = createdAt;
    this.deletedAt = deletedAt;
    this.id = id;
    this.updatedAt = updatedAt;
  }

  /**
   * Account Schedule ID.
   * @return accountScheduleId
   */
  @javax.annotation.Nullable
  public String getAccountScheduleId() {
    return accountScheduleId;
  }



  public DdidnsrickettsSourceConfig accounts(@javax.annotation.Nullable List<DdidnsrickettsAccount> accounts) {
    this.accounts = accounts;
    return this;
  }

  public DdidnsrickettsSourceConfig addAccountsItem(DdidnsrickettsAccount accountsItem) {
    if (this.accounts == null) {
      this.accounts = new ArrayList<>();
    }
    this.accounts.add(accountsItem);
    return this;
  }

  /**
   * Get accounts
   * @return accounts
   */
  @javax.annotation.Nullable
  public List<DdidnsrickettsAccount> getAccounts() {
    return accounts;
  }

  public void setAccounts(@javax.annotation.Nullable List<DdidnsrickettsAccount> accounts) {
    this.accounts = accounts;
  }


  public DdidnsrickettsSourceConfig cloudCredentialId(@javax.annotation.Nonnull String cloudCredentialId) {
    this.cloudCredentialId = cloudCredentialId;
    return this;
  }

  /**
   * Cloud Credential ID.
   * @return cloudCredentialId
   */
  @javax.annotation.Nonnull
  public String getCloudCredentialId() {
    return cloudCredentialId;
  }

  public void setCloudCredentialId(@javax.annotation.Nonnull String cloudCredentialId) {
    this.cloudCredentialId = cloudCredentialId;
  }


  /**
   * Timestamp when the object has been created.
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  public DdidnsrickettsSourceConfig credentialConfig(@javax.annotation.Nullable DdidnsrickettsCredentialConfig credentialConfig) {
    this.credentialConfig = credentialConfig;
    return this;
  }

  /**
   * Get credentialConfig
   * @return credentialConfig
   */
  @javax.annotation.Nullable
  public DdidnsrickettsCredentialConfig getCredentialConfig() {
    return credentialConfig;
  }

  public void setCredentialConfig(@javax.annotation.Nullable DdidnsrickettsCredentialConfig credentialConfig) {
    this.credentialConfig = credentialConfig;
  }


  /**
   * Timestamp when the object has been deleted.
   * @return deletedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }



  /**
   * Auto-generated unique source config ID. Format BloxID.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }



  public DdidnsrickettsSourceConfig restrictedToAccounts(@javax.annotation.Nullable List<String> restrictedToAccounts) {
    this.restrictedToAccounts = restrictedToAccounts;
    return this;
  }

  public DdidnsrickettsSourceConfig addRestrictedToAccountsItem(String restrictedToAccountsItem) {
    if (this.restrictedToAccounts == null) {
      this.restrictedToAccounts = new ArrayList<>();
    }
    this.restrictedToAccounts.add(restrictedToAccountsItem);
    return this;
  }

  /**
   * Provider account IDs such as accountID/ SubscriptionID to be restricted for a given source_config.
   * @return restrictedToAccounts
   */
  @javax.annotation.Nullable
  public List<String> getRestrictedToAccounts() {
    return restrictedToAccounts;
  }

  public void setRestrictedToAccounts(@javax.annotation.Nullable List<String> restrictedToAccounts) {
    this.restrictedToAccounts = restrictedToAccounts;
  }


  /**
   * Timestamp when the object has been updated.
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DdidnsrickettsSourceConfig ddidnsrickettsSourceConfig = (DdidnsrickettsSourceConfig) o;
    return Objects.equals(this.accountScheduleId, ddidnsrickettsSourceConfig.accountScheduleId) &&
        Objects.equals(this.accounts, ddidnsrickettsSourceConfig.accounts) &&
        Objects.equals(this.cloudCredentialId, ddidnsrickettsSourceConfig.cloudCredentialId) &&
        Objects.equals(this.createdAt, ddidnsrickettsSourceConfig.createdAt) &&
        Objects.equals(this.credentialConfig, ddidnsrickettsSourceConfig.credentialConfig) &&
        Objects.equals(this.deletedAt, ddidnsrickettsSourceConfig.deletedAt) &&
        Objects.equals(this.id, ddidnsrickettsSourceConfig.id) &&
        Objects.equals(this.restrictedToAccounts, ddidnsrickettsSourceConfig.restrictedToAccounts) &&
        Objects.equals(this.updatedAt, ddidnsrickettsSourceConfig.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountScheduleId, accounts, cloudCredentialId, createdAt, credentialConfig, deletedAt, id, restrictedToAccounts, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DdidnsrickettsSourceConfig {\n");
    sb.append("    accountScheduleId: ").append(toIndentedString(accountScheduleId)).append("\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("    cloudCredentialId: ").append(toIndentedString(cloudCredentialId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    credentialConfig: ").append(toIndentedString(credentialConfig)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    restrictedToAccounts: ").append(toIndentedString(restrictedToAccounts)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("account_schedule_id");
    openapiFields.add("accounts");
    openapiFields.add("cloud_credential_id");
    openapiFields.add("created_at");
    openapiFields.add("credential_config");
    openapiFields.add("deleted_at");
    openapiFields.add("id");
    openapiFields.add("restricted_to_accounts");
    openapiFields.add("updated_at");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("cloud_credential_id");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DdidnsrickettsSourceConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DdidnsrickettsSourceConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DdidnsrickettsSourceConfig is not found in the empty JSON string", DdidnsrickettsSourceConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DdidnsrickettsSourceConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DdidnsrickettsSourceConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DdidnsrickettsSourceConfig.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("account_schedule_id") != null && !jsonObj.get("account_schedule_id").isJsonNull()) && !jsonObj.get("account_schedule_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `account_schedule_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_schedule_id").toString()));
      }
      if (jsonObj.get("accounts") != null && !jsonObj.get("accounts").isJsonNull()) {
        JsonArray jsonArrayaccounts = jsonObj.getAsJsonArray("accounts");
        if (jsonArrayaccounts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("accounts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `accounts` to be an array in the JSON string but got `%s`", jsonObj.get("accounts").toString()));
          }

          // validate the optional field `accounts` (array)
          for (int i = 0; i < jsonArrayaccounts.size(); i++) {
            DdidnsrickettsAccount.validateJsonElement(jsonArrayaccounts.get(i));
          };
        }
      }
      if (!jsonObj.get("cloud_credential_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cloud_credential_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cloud_credential_id").toString()));
      }
      // validate the optional field `credential_config`
      if (jsonObj.get("credential_config") != null && !jsonObj.get("credential_config").isJsonNull()) {
        DdidnsrickettsCredentialConfig.validateJsonElement(jsonObj.get("credential_config"));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("restricted_to_accounts") != null && !jsonObj.get("restricted_to_accounts").isJsonNull() && !jsonObj.get("restricted_to_accounts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `restricted_to_accounts` to be an array in the JSON string but got `%s`", jsonObj.get("restricted_to_accounts").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DdidnsrickettsSourceConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DdidnsrickettsSourceConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DdidnsrickettsSourceConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DdidnsrickettsSourceConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<DdidnsrickettsSourceConfig>() {
           @Override
           public void write(JsonWriter out, DdidnsrickettsSourceConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DdidnsrickettsSourceConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DdidnsrickettsSourceConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DdidnsrickettsSourceConfig
   * @throws IOException if the JSON string is invalid with respect to DdidnsrickettsSourceConfig
   */
  public static DdidnsrickettsSourceConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DdidnsrickettsSourceConfig.class);
  }

  /**
   * Convert an instance of DdidnsrickettsSourceConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

