/*
 * Cloud DNS Forwarder API
 * Allows configuring resources to forward DNS queries from Cloud Providers to B1DDI/NIOS
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.DdiCloudDnsForwarderIpAddress;
import org.openapitools.client.model.DdiCloudDnsForwarderPrivateNetwork;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DdiCloudDnsForwarderRule
 */
public class DdiCloudDnsForwarderRuleTest {
    private final DdiCloudDnsForwarderRule model = new DdiCloudDnsForwarderRule();

    /**
     * Model tests for DdiCloudDnsForwarderRule
     */
    @Test
    public void testDdiCloudDnsForwarderRule() {
        // TODO: test DdiCloudDnsForwarderRule
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'destinationIps'
     */
    @Test
    public void destinationIpsTest() {
        // TODO: test destinationIps
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    public void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'endpointId'
     */
    @Test
    public void endpointIdTest() {
        // TODO: test endpointId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'identityAccountId'
     */
    @Test
    public void identityAccountIdTest() {
        // TODO: test identityAccountId
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'providerRuleId'
     */
    @Test
    public void providerRuleIdTest() {
        // TODO: test providerRuleId
    }

    /**
     * Test the property 'providerVirtualNetworks'
     */
    @Test
    public void providerVirtualNetworksTest() {
        // TODO: test providerVirtualNetworks
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'zoneId'
     */
    @Test
    public void zoneIdTest() {
        // TODO: test zoneId
    }

}
